version: '3.7'

volumes:
  postgresdata:
      external: false

services:
    test-api:
      volumes:
        - ./src:/app/src:z
        - ./package.json:/app/package.json:z
        - ./tsconfig.json:/app/tsconfig.json:z
        - ./jest.config.js:/app/jest.config.js:z
        - ./build:/app/build:z
        - ./migrations:/app/migrations:z
      ports:
          - 3000:3000
    test-db:
      restart: always
      volumes:
        - postgresdata:/var/lib/postgresql/data/pgdata:Z
      ports:
        - 5433:5432