name: ci

on:
    pull_request:
        branches: [ master ]
env:
  BUILD_IMAGE: "docker.pkg.github.com/${{github.repository}}/awesome_image:pr-${{github.event.number}}.api.${{ github.sha }}"

jobs:
  cancel-previous-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    env:
      MAIN_CACHE_PATH: /tmp/.buildx-cache/main  
    steps:
    - name: Builder
      uses: docker/setup-buildx-action@v1
      id: buildx

    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ${{ env.MAIN_CACHE_PATH }}
        key: ${{ runner.os }}-buildx-main-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-main-
    
    - name: Temp tags
      id: tmpimg
      run: |
        MAIN_TAG="main-$GITHUB_SHA"
        DB_TAG="db-$GITHUB_SHA"
        echo ::set-output name=mainimg::${MAIN_TAG}
        echo ::set-output name=dbimg::${DB_TAG}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build source
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        target: build
        push: true
        cache-from: type=local,src=${{ env.MAIN_CACHE_PATH }}
        cache-to: type=local,mode=max,dest=${{ env.MAIN_CACHE_PATH }}
        tags: ${{ env.BUILD_IMAGE }}
